#!/usr/bin/env python3
"""
Fast plotting script for fig_bulk0/fig_clump0 uncertainty regions.

This script does NOT run the ODE. It reads cached trajectory CSV files generated by:
    cache_fig0_uncertainty_trajectories_fast_v2.py

Main changes in this version:
    - Experimental points with labels "AOM_P_LS" and "AOM_Wegner_LS"
      are plotted together as the single series "AOM_LS".
    - Colors, line styles, marker styles, and legend labels are all defined
      in the USER SETTINGS section so you can edit them directly.
"""

# =============================================================================
# USER SETTINGS
# =============================================================================

DATA_CSV = "isotope_data.csv"

CACHE_PREFIX = "fig0_uncertainty_cache"
OUT_PREFIX = "fig0_uncertainty_from_cache"

# These names should match the cached model series names.
# AOM_LS uses the cached model file:
#     fig0_uncertainty_cache_AOM_LS_trajectories.csv
SERIES_TO_PLOT = ["ANME2d", "AOM_P", "AOM_LS"]

# Experimental labels in isotope_data.csv that should be plotted for each series.
# You can include more than one CSV label per plotted series.
# Here, AOM_P_LS and AOM_Wegner_LS are combined and plotted as AOM_LS.
SERIES_DATA_LABELS = {
    "ANME2d": ["3"],
    "AOM_P": ["AOM_P"],
    "AOM_LS": ["AOM_P_LS", "AOM_Wegner_LS", "AOM_Wegener_LS"],
}

# Legend names for each plotted series.
# Edit these strings to change how each series appears in the legend.
SERIES_DISPLAY_LABELS = {
    "ANME2d": "N-AOM",
    "AOM_P": "S-AOM (high sulfate)",
    "AOM_LS": "S-AOM (low sulfate)",
}

# Separate legend labels for model region, central model line, and data.
# Set any value to None if you do not want that item to appear in the legend.
SERIES_REGION_LABELS = {
    "ANME2d": None,
    "AOM_P": None,
    "AOM_LS": None,
}

SERIES_MODEL_LABELS = {
    "ANME2d": r"Model []",
    "AOM_P": r"Model []",
    "AOM_LS": r"Model []",
}

SERIES_DATA_LABELS_FOR_LEGEND = {
    "ANME2d": " N-AOM",
    "AOM_P": "S-AOM (high sulfate)",
    "AOM_LS": "S-AOM (low sulfate)",
}

# Colors.
# Use any Matplotlib color name, hex code, or RGB/RGBA tuple.
# Examples: "black", "tab:blue", "#1f77b4", (0.2, 0.4, 0.8)
SERIES_COLORS = {
    "ANME2d": "tab:blue",
    "AOM_P": "tab:orange",
    "AOM_LS": "tab:green",
}

# Optional separate colors for uncertainty regions.
# Set a value to None to use SERIES_COLORS for that series.
SERIES_REGION_COLORS = {
    "ANME2d": None,
    "AOM_P": None,
    "AOM_LS": None,
}

# Central model line styles.
SERIES_LINESTYLES = {
    "ANME2d": "-",
    "AOM_P": "--",
    "AOM_LS": "-.",
}

SERIES_LINEWIDTHS = {
    "ANME2d": 2.5,
    "AOM_P": 2.5,
    "AOM_LS": 2.5,
}

# Experimental marker styles.
SERIES_MARKERS = {
    "ANME2d": "o",
    "AOM_P": "s",
    "AOM_LS": "^",
}

SERIES_MARKER_SIZES = {
    "ANME2d": 14,
    "AOM_P": 14,
    "AOM_LS": 14,
}

# Marker face and edge colors.
# Set a value to None to use SERIES_COLORS for that series.
SERIES_MARKER_FACE_COLORS = {
    "ANME2d": None,
    "AOM_P": None,
    "AOM_LS": None,
}

SERIES_MARKER_EDGE_COLORS = {
    "ANME2d": "black",
    "AOM_P": "black",
    "AOM_LS": "black",
}

SERIES_MARKER_EDGE_WIDTHS = {
    "ANME2d": 1.0,
    "AOM_P": 1.0,
    "AOM_LS": 1.0,
}

# Region transparency.
REGION_ALPHA = 0.18

N_SIGMA_TO_PLOT = 1.0
EXCLUDE_INITIAL_DATA_FROM_PLOT = False

# If True, plot model region even when experimental transformed data are missing.
PLOT_MODEL_WITHOUT_DATA = True

XLIM_BULK = None
YLIM_BULK = None
XLIM_CLUMP = None
YLIM_CLUMP = None

# =============================================================================
# END USER SETTINGS
# =============================================================================

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


TRANSFORMED_COLS = ["ln(c/c0)", "ln(d/d0)", "DeltaCD", "DeltaDD"]


def style_value(style_dict, series, default=None):
    """Return a style value for a series, with a safe default."""
    value = style_dict.get(series, default)
    return default if value is None else value


def display_label(series):
    """Return the user-defined display label for a series."""
    return SERIES_DISPLAY_LABELS.get(series, series)


def load_settings():
    path = Path(f"{CACHE_PREFIX}_settings.csv")
    if not path.exists():
        raise FileNotFoundError(f"Missing settings file: {path}")
    settings = pd.read_csv(path)
    return {row["series"]: row for _, row in settings.iterrows()}


def load_cached_series(series):
    path = Path(f"{CACHE_PREFIX}_{series}_trajectories.csv")
    if not path.exists():
        if PLOT_MODEL_WITHOUT_DATA:
            print(f"Warning: missing cached trajectory file for {series}: {path}")
            return None
        raise FileNotFoundError(f"Missing cached trajectory file: {path}")
    return pd.read_csv(path)


def get_run(df, run_name):
    sub = df[df["run_name"] == run_name].copy()
    if sub.empty:
        return None
    return sub.sort_values("f").reset_index(drop=True)


def add_variance_from_pair(variance, plus, minus, sigma, param_value_plus, param_value_minus):
    if plus is None or minus is None:
        return

    h = float(param_value_plus - param_value_minus)
    if h <= 0:
        return

    for col in TRANSFORMED_COLS:
        derivative = (plus[col].to_numpy() - minus[col].to_numpy()) / h
        variance[col] += (derivative * sigma) ** 2


def add_variance_one_sided(variance, central, perturbed, sigma, param_value_perturbed, param_value_central):
    """
    Use one-sided finite difference if the central value is near a bound and
    only plus or minus exists.
    """
    if central is None or perturbed is None:
        return

    h = float(param_value_perturbed - param_value_central)
    if h == 0:
        return

    for col in TRANSFORMED_COLS:
        derivative = (perturbed[col].to_numpy() - central[col].to_numpy()) / h
        variance[col] += (derivative * sigma) ** 2


def region_from_cache(df, settings_row):
    central = get_run(df, "central")
    if central is None:
        raise ValueError("Cached file does not contain run_name='central'.")

    variance = {col: np.zeros(len(central), dtype=float) for col in TRANSFORMED_COLS}

    for p in ["rev1", "rev2", "rev3"]:
        plus = get_run(df, f"{p}_plus")
        minus = get_run(df, f"{p}_minus")
        sigma = float(settings_row[f"sigma_{p}"])
        central_value = float(settings_row[p])

        if plus is not None and minus is not None:
            add_variance_from_pair(
                variance=variance,
                plus=plus,
                minus=minus,
                sigma=sigma,
                param_value_plus=float(plus[p].iloc[0]),
                param_value_minus=float(minus[p].iloc[0]),
            )
        elif plus is not None:
            add_variance_one_sided(
                variance=variance,
                central=central,
                perturbed=plus,
                sigma=sigma,
                param_value_perturbed=float(plus[p].iloc[0]),
                param_value_central=central_value,
            )
        elif minus is not None:
            add_variance_one_sided(
                variance=variance,
                central=central,
                perturbed=minus,
                sigma=sigma,
                param_value_perturbed=float(minus[p].iloc[0]),
                param_value_central=central_value,
            )

    for p, sigma_col in [
        ("gammaCDff2", "sigma_gammaCDff2"),
        ("gammaDDff2", "sigma_gammaDDff2"),
    ]:
        plus = get_run(df, f"{p}_plus")
        minus = get_run(df, f"{p}_minus")
        sigma = float(settings_row[sigma_col])
        central_value = float(settings_row[p])

        if plus is not None and minus is not None:
            add_variance_from_pair(
                variance=variance,
                plus=plus,
                minus=minus,
                sigma=sigma,
                param_value_plus=float(plus[p].iloc[0]),
                param_value_minus=float(minus[p].iloc[0]),
            )
        elif plus is not None:
            add_variance_one_sided(
                variance=variance,
                central=central,
                perturbed=plus,
                sigma=sigma,
                param_value_perturbed=float(plus[p].iloc[0]),
                param_value_central=central_value,
            )
        elif minus is not None:
            add_variance_one_sided(
                variance=variance,
                central=central,
                perturbed=minus,
                sigma=sigma,
                param_value_perturbed=float(minus[p].iloc[0]),
                param_value_central=central_value,
            )

    region = pd.DataFrame({"f": central["f"].to_numpy()})

    for col in TRANSFORMED_COLS:
        mid = central[col].to_numpy()
        sd = np.sqrt(variance[col])
        region[f"{col}_mid"] = mid
        region[f"{col}_sigma"] = sd
        region[f"{col}_lo"] = mid - N_SIGMA_TO_PLOT * sd
        region[f"{col}_hi"] = mid + N_SIGMA_TO_PLOT * sd

    return region


def draw_parametric_region(ax, x_lo, y_lo, x_hi, y_hi, label=None, alpha=0.18, color=None):
    x_poly = np.r_[x_lo, x_hi[::-1]]
    y_poly = np.r_[y_lo, y_hi[::-1]]
    ax.fill(x_poly, y_poly, alpha=alpha, label=label, color=color, linewidth=0)


def get_valid_data_for_series(data, series):
    csv_labels = SERIES_DATA_LABELS.get(series, [series])
    csv_labels = [str(x) for x in csv_labels]

    df = data[data["label"].astype(str).str.strip().isin(csv_labels)].copy()

    if df.empty:
        return pd.DataFrame()

    # Convert numeric columns, but do not drop rows here.
    # Different plots need different columns: AOM_Wegener_LS has valid bulk
    # transformed data but blank clumped-isotope columns. Dropping all
    # TRANSFORMED_COLS here would wrongly remove it from the bulk plot.
    optional_numeric_cols = ["f", "lncse", "lndse", "fse", "se"]
    for col in TRANSFORMED_COLS + optional_numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    if EXCLUDE_INITIAL_DATA_FROM_PLOT and "f" in df.columns:
        df = df[(df["f"].isna()) | (df["f"] < 0.999999)].copy()

    return df


def plot_model_and_data(ax, series, reg, df, x_col, y_col, xerr_col=None, yerr_col=None):
    color = style_value(SERIES_COLORS, series, None)
    region_color = style_value(SERIES_REGION_COLORS, series, color)
    linestyle = style_value(SERIES_LINESTYLES, series, "-")
    linewidth = style_value(SERIES_LINEWIDTHS, series, 2.5)
    marker = style_value(SERIES_MARKERS, series, "o")
    markersize = style_value(SERIES_MARKER_SIZES, series, 9)
    markerfacecolor = style_value(SERIES_MARKER_FACE_COLORS, series, color)
    markeredgecolor = style_value(SERIES_MARKER_EDGE_COLORS, series, color)
    markeredgewidth = style_value(SERIES_MARKER_EDGE_WIDTHS, series, 1.0)

    draw_parametric_region(
        ax,
        reg[f"{x_col}_lo"],
        reg[f"{y_col}_lo"],
        reg[f"{x_col}_hi"],
        reg[f"{y_col}_hi"],
        label=SERIES_REGION_LABELS.get(
            series,
            f"{display_label(series)} ±{N_SIGMA_TO_PLOT:g}σ region",
        ),
        alpha=REGION_ALPHA,
        color=region_color,
    )

    ax.plot(
        reg[f"{x_col}_mid"],
        reg[f"{y_col}_mid"],
        color=color,
        linestyle=linestyle,
        linewidth=linewidth,
        label=SERIES_MODEL_LABELS.get(series, f"{display_label(series)} central model"),
    )

    if not df.empty:
        plot_df = df.dropna(subset=[x_col, y_col]).copy()

        if not plot_df.empty:
            xerr = plot_df[xerr_col] if xerr_col is not None and xerr_col in plot_df.columns else None
            yerr = plot_df[yerr_col] if yerr_col is not None and yerr_col in plot_df.columns else None

            ax.errorbar(
                plot_df[x_col],
                plot_df[y_col],
                xerr=xerr,
                yerr=yerr,
                fmt=marker,
                linestyle="none",
                color=color,
                markerfacecolor=markerfacecolor,
                markeredgecolor=markeredgecolor,
                markeredgewidth=markeredgewidth,
                markersize=markersize,
                capsize=0,
                label=SERIES_DATA_LABELS_FOR_LEGEND.get(series, f"{display_label(series)} data"),
            )
        else:
            print(f"  no valid {x_col} / {y_col} experimental data for {series}; plotting model only.")
    else:
        print(f"  no experimental rows matched labels for {series}; plotting model only.")


def main():
    data = pd.read_csv(DATA_CSV)
    settings = load_settings()

    regions = {}
    actual_series = []

    for series in SERIES_TO_PLOT:
        print(f"Reading cached trajectories for {series}...")
        cached = load_cached_series(series)
        if cached is None:
            continue
        if series not in settings:
            print(f"Warning: no settings row found for {series}; skipping.")
            continue
        regions[series] = region_from_cache(cached, settings[series])
        actual_series.append(series)

    if not actual_series:
        raise RuntimeError("No cached model regions were loaded.")

    fig_bulk0, ax_bulk0 = plt.subplots(figsize=(12, 12))

    for series in actual_series:
        df = get_valid_data_for_series(data, series)
        reg = regions[series]
        plot_model_and_data(
            ax=ax_bulk0,
            series=series,
            reg=reg,
            df=df,
            x_col="ln(c/c0)",
            y_col="ln(d/d0)",
            xerr_col="lncse",
            yerr_col="lndse",
        )

    ax_bulk0.set_xlabel(
        r'ln$\frac{\delta^{13}{\rm C}+1000}{\delta^{13}{\rm C}_{\rm init}+1000}$',
        fontsize=18,
    )
    ax_bulk0.set_ylabel(
        r'ln$\frac{\delta{\rm D}+1000}{\delta{\rm D}_{\rm init}+1000}$',
        fontsize=18,
    )
    ax_bulk0.tick_params(which="major", direction="out", top=True, right=True, labelsize=14)
    ax_bulk0.tick_params(which="minor", direction="out", top=True, right=True)
    if XLIM_BULK is not None:
        ax_bulk0.set_xlim(XLIM_BULK)
    if YLIM_BULK is not None:
        ax_bulk0.set_ylim(YLIM_BULK)
    ax_bulk0.legend(fontsize=10)
    fig_bulk0.tight_layout()

    fig_clump0, ax_clump0 = plt.subplots(figsize=(12, 12))

    for series in actual_series:
        df = get_valid_data_for_series(data, series)
        reg = regions[series]
        plot_model_and_data(
            ax=ax_clump0,
            series=series,
            reg=reg,
            df=df,
            x_col="DeltaCD",
            y_col="DeltaDD",
        )

    ax_clump0.set_xlabel(r'$\Delta \Delta^{13}$CH$_3$D (‰)', fontsize=18)
    ax_clump0.set_ylabel(r'$\Delta \Delta^{12}$CH$_2$D$_2$ (‰)', fontsize=18)
    ax_clump0.tick_params(which="major", direction="out", top=True, right=True, labelsize=14)
    ax_clump0.tick_params(which="minor", direction="out", top=True, right=True)
    if XLIM_CLUMP is not None:
        ax_clump0.set_xlim(XLIM_CLUMP)
    if YLIM_CLUMP is not None:
        ax_clump0.set_ylim(YLIM_CLUMP)
    ax_clump0.legend(fontsize=10)
    fig_clump0.tight_layout()

    bulk_path = f"{OUT_PREFIX}_fig_bulk0_uncertainty.pdf"
    clump_path = f"{OUT_PREFIX}_fig_clump0_uncertainty.pdf"

    fig_bulk0.savefig(bulk_path)
    fig_clump0.savefig(clump_path)

    print("\nSaved:")
    print(f"  {bulk_path}")
    print(f"  {clump_path}")


if __name__ == "__main__":
    main()
